on:
  push:
    branches:
      - frontend
name: Deploy
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftpfront_host }}
          username: ${{ secrets.ftpfront_username }}
          password: ${{ secrets.ftpfront_password }}
